### PR TITLE
update KMD daemon

### PR DESCRIPTION
**Pull request by wbpxre150**

### CODE REVIEW

**Comment by phm87** [comment]
I think that we should include https://github.com/KomodoPlatform/komodo/pull/380 = update to same code as NN are using + dpowlistunspent rpc call
https://github.com/KomodoPlatform/komodo/compare/master...phm87:blackjok3r_dpowlistunspent

Based on what I read in KMDLabs repository, I think that if some changes are added to KMDLabs/komodo and that KMD Labs notaries perform a git pull, then they should have the new code. Is it correct or does it use another repo?

Note: I'd like to test ac_aur (future ac param to have active user rewards on smartchains) and test compatibility with ac_notary
https://github.com/KomodoPlatform/komodo/compare/master...phm87:ac_aur

**Comment by wbpxre150** [comment]
This is not nessary please do not re open it

**Comment by phm87** [comment]
@wbpxre150 I think that this repository does not contain the new KMD Notary keys so it should be stuck at the last KMD HF.

https://github.com/KMDLabs/komodo/blob/master/src/komodo_defs.h#L261

**Comment by wbpxre150** [comment]
Yes, Alright merged the wrong PR, one that was not even open or created by me some how. Anyway, Ill revert his revert later and await commit access to delete this repo to avoid any more confusion over the matter.

**Pull request closed without merging**
